services:
  whisper-api:
    build:
      context: Container_Folder/Faster_Whisper
      dockerfile: dockerfile
    image: tructran172003/whisper-api:latest
    ports:
      - "8000:8000"
    networks:
      - my-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all # This corresponds to --gpus all

  tts-api:
    build:
      context: Container_Folder/Text_to_Speech
      dockerfile: dockerfile
    image: tructran172003/tts-api:latest
    ports:
      - "8001:8001"
    networks:
      - my-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all # This corresponds to --gpus all

  chatbot_api:
    build:
      context: Container_Folder/chatbot_api
      dockerfile: dockerfile
    image: tructran172003/chatbot-api:latest
    env_file:
      - ./config/.env
    ports:
      - "4096:4096"
    depends_on:
      - db
      - whisper-api
      - tts-api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    networks:
      - my-network


  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-rag:latest
    restart: always
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
    # Defines a volume to persist the database data.
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge

