services:
  whisper-api:
    build:
      context: ../RAG_Project/Container_Folder/Faster_Whisper
      dockerfile: dockerfile
    image: tructran172003/whisper-api:v1.0
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 
              count: all # This corresponds to --gpus all
