services:
  # whisper-api:
  #   build:
  #     context: ../RAG_Project/Container_Folder/Faster_Whisper
  #     dockerfile: dockerfile
  #   image: tructran172003/whisper-api:v1.0
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - my-network
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu] 
  #             count: all # This corresponds to --gpus all

  # tts-api:
  #   build:
  #     context: ../RAG_Project/Container_Folder/Text_to_Speech
  #     dockerfile: dockerfile
  #   image: tructran172003/tts-api:v1.0
  #   ports:
  #     - "8001:8001"
  #   networks:
  #     - my-network
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu] 
  #             count: all # This corresponds to --gpus all

  # chatbot_api:
  #   build:
  #     context: ../RAG_Project/Container_Folder/chatbot_api
  #     dockerfile: dockerfile
  #   image: tructran172003/chatbot-api:v1.0
  #   env_file:
  #     - ./config/.env
  #   ports:
  #     - "4096:4096"
  #   depends_on:
  #     - db
  #     - whisper-api
  #     - tts-api
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]
  #             count: all
  #   networks:
  #     - my-network


  # db:
  #   image: pgvector/pgvector:pg16
  #   container_name: pgvector-rag
  #   restart: always
  #   env_file:
  #     - ./config/.env
  #   ports:
  #     - "5432:5432"
  #   # Defines a volume to persist the database data.
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - my-network

  jenkins:
    build:
        context: ./Container_Folder/jenkin_upgrade
        dockerfile: dockerfile
    image: tructran172003/jenkin:v1.0
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge

